site_name: Grupo de Radio-frecuencia, Micro-ondas y Óptica
site_author: Roosevelt J. Ubaldo Chavez
site_description: Página web del Grupo de Investigación en Computación GIC

# repo_name: squidfunk/mkdocs-material
# repo_url: https://github.com/squidfunk/mkdocs-material
nav:
  - Inicio: index.md
  - Nosotros: about.md
  - Investigación: research
  - Publicaciones: publications.md
  - Miembros: people
  - Noticias & Eventos: news-and-events.md
  - Contacto: contact-us.md
extra_css:
  - stylesheets/neoteroi-mkdocs.css
  - stylesheets/extra.css

extra_javascript:
  - https://platform.twitter.com/widgets.js

theme:
  logo: assets/grfmo-logo-white.svg
  favicon: assets/grfmo-logo-white.svg
  name: material
  custom_dir: overrides
  language: es
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - navigation.path
    - navigation.top

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/GRFMO
      name: GRFMO on GiHub
  generator: false

plugins:
  - search:
      lang: 
        - en
        - es
  - i18n:
      languages:
        - locale: es
          default: true
          name: Español
          build: true
        # - locale: en
        #   name: English
        #   build: true
        #   site_name:  Radio-frecuency, Micro-waves and Optics Group
        #   nav:
        #     - Home: en/index.md
        #     - About us: en/about.md
        #     - News & Events: en/news-and-events.md
        #     - Research: en/research
        #     - Publications: en/publications.md
        #     - People: en/people
        #     - Contact: en/contact-us.md


markdown_extensions: 
  - attr_list
  - md_in_html
  - neoteroi.cards
  - neoteroi.timeline


copyright: Copyright &copy; 2023 Radio-frecuency, Micro-waves and Optics Groups
