site_name: G-RFMO
site_subtitle: Grupo de Radio-frecuencia, Micro-ondas y Óptica del Instituto Nacional de Investigación y Capacitación de Telecomunicaciones de la Universidad Nacional de Ingeniería (INICTEL-UNI)
site_description: >
 El Área de Investigación de Radiofrecuencia, Microondas y Óptica se dedica a investigar nuevos conceptos, métodos, técnicas para el diseño, fabricación y caracterización de la interacción entre la onda electromagnética y materiales para diferentes rangos de frecuencia en aplicaciones críticas. El trabajo del grupo está enmarcado dentro de tres grandes áreas: materiales, dispositivos y subsistemas.

# repo_name: squidfunk/mkdocs-material
# repo_url: https://github.com/squidfunk/mkdocs-material
nav:
  - index.md
  - Nosotros: about/index.md
  - Investigación: research/index.md
  - Publicaciones: 
    - publications/index.md
    - Conferencias: publications/conferences.md
    - Journals: publications/journals.md
  - Miembros: people/index.md
  - Alumni: alumni/index.md
  - Noticias & Eventos: news-and-events/index.md
  - Virtual Lab: virtual-lab.md
  - Contacto: contact-us/index.md

  # - Blog:
  #   - blog/index.md 

theme:
  name: material
  logo: assets/logos/grfmo-logo-white.svg
  favicon: assets/logos/grfmo-logo-white.svg
  custom_dir: overrides
  language: es
  palette: 
    
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: grfmo 
      accent: blue
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: grfmo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - toc.follow
    - navigation.top
    - announce.dismiss
    - navigation.footer

plugins:
  - search:
      lang: 
        - es
  - blog
  - macros
  # - blog
  # - i18n:
  #     docs_structure: folder
  #     languages:
  #       - locale: es
  #         default: true
  #         name: Español
  #         build: true
        # - locale: en
        #   name: English
        #   build: true
        #   site_name:  Radio-frecuency, Micro-waves and Optics Group
        #   nav:
        #     - Home: en/index.md
        #     - About us: en/about.md
        #     - News & Events: en/news-and-events.md
        #     - Research: en/research
        #     - Publications: en/publications.md
        #     - People: en/people
        #     - Contact: en/contact-us.md

extra:
  # consent:
  #   title: Cookie consent
  #   description: >- 
  #     We use cookies to recognize your repeated visits and preferences, as well
  #     as to measure the effectiveness of our documentation and whether users
  #     find what they're searching for. With your consent, you're helping us to
  #     make our documentation better.
  # alternate:
  #   - name: English
  #     link: /en/ 
  #     lang: en
  #   - name: Español
  #     link: /
  #     lang: es
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/GRFMO
      name: GRFMO on GiHub
  # disable made with material
  generator: true
  header_image_src: /assets/home-bg.webp

markdown_extensions: 
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - neoteroi.cards
  - neoteroi.timeline
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra_css:
  - assets/stylesheets/neoteroi-mkdocs.css
  - assets/stylesheets/extra.css

copyright: Copyright &copy; 2023 Radio-frecuency, Micro-waves and Optics Groups
